# oc secrets link -n pipeline-ci pipeline quay-pull-secret
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: pipeline
  namespace: pipeline-ci
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
secret:
  - name: quay-pull-secret