apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: discounts-template
spec:
  params:
  - name: git-repo-url
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: pipeline-discounts-
    spec:
      pipelineRef:
        name: build-quarkus-application
      params:
      - name: SOURCE_GIT_URL
        value: $(tt.params.git-repo-url)
      - name: APP_NAME
        value: discounts
      workspaces:
      - name: dockerconfig
        secret:
          secretName: docker-config
      - name: app-source
        persistentVolumeClaim:
          claimName: workspace-pvc
      - name: maven-settings
        emptyDir: {}
