apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-quarkus-application
spec:
  params:
  - name: APP_NAME
    type: string
    description: The application deployment name
  - name: SOURCE_GIT_URL
    type: string
    description: The application git repository url
    default: https://github.com/davidseve/poc-quarkus-applications
  - name: SOURCE_GIT_REVISION
    type: string
    default: main
    description: The application git repository revision
  - name: SOURCE_GIT_CONTEXT_DIR
    type: string
    default: ""
    description: The subdirectory in the git repository
  - name: IMAGE
    type: string
    default: quay.io/dseveria/
    description: Image registry
  - name: TAG
    type: string
    default: latest
    description: Image tag
  - name: DOCKERFILE
    type: string
    default: src/main/docker/Dockerfile.jvm
    description: Docker file path


  workspaces:
  - name: workspace-source
  - name: maven_settings  

  tasks:
  - name: git-clone
    params:
      - name: URL
        value: $(params.SOURCE_GIT_URL)
      - name: REVISION
        value: $(params.SOURCE_GIT_REVISION)
      - name: DELETE_EXISTING
        value: 'true'
    taskRef:
      params:
        - name: name
          value: git-clone
        - name: namespace
          value: openshift-pipelines
      resolver: cluster
    workspaces:
      - name: output
        workspace: workspace-source
  
  - name: package
    runAfter:
      - git-clone
    params:
      - name: SUBDIRECTORY
        value: ./$(params.SOURCE_GIT_CONTEXT_DIR)
    taskRef:
      params:
        - name: name
          value: maven
        - name: namespace
          value: openshift-pipelines
      resolver: cluster      
    workspaces:
      - name: source
        workspace: workspace-source
      - name: maven_settings
        workspace: maven_settings

  - name: build-sign-image
    params:
      - name: IMAGE
        value: $(params.IMAGE)$(params.APP_NAME):$(params.TAG)
      - name: CONTEXT
        value: ./$(params.SOURCE_GIT_CONTEXT_DIR)
      - name: DOCKERFILE
        value: ./$(SOURCE_GIT_CONTEXT_DIR)/$(params.DOCKERFILE)
    runAfter:
      - package
    taskRef:
      resolver: cluster
      params:
        - name: name
          value: buildah
        - name: namespace
          value: openshift-pipelines          
    workspaces:
      - name: source
        workspace: workspace-source