apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-quarkus-application
  namespace: openshift-gitops
spec:
  params:
  - name: APP_NAME
    type: string
    description: The application deployment name
  - name: SOURCE_GIT_URL
    type: string
    description: The application git repository url
    default: https://github.com/davidseve/poc-quarkus-applications
  - name: SOURCE_GIT_REVISION
    type: string
    default: main
    description: The application git repository revision
  - name: SOURCE_GIT_CONTEXT_DIR
    type: string
    default: ""
    description: The subdirectory in the git repository
  - name: IMAGE
    type: string
    default: quay.io/dseveria/
    description: Image registry
  - name: TAG
    type: string
    default: latest
    description: Image tag
  - name: DOCKERFILE
    type: string
    default: src/main/docker/Dockerfile.jvm
    description: Docker file path


  workspaces:
  - name: workspace-source

  tasks:
  - name: fetch-repository
    params:
      - name: URL
        value: $(params.SOURCE_GIT_URL)
      - name: REVISION
        value: $(params.SOURCE_GIT_REVISION)
      - name: DELETE_EXISTING
        value: 'true'
      # - name: SSL_VERIFY
      #   value: $(params.GIT_SSL_VERIFY)
    taskRef:
      params:
        - name: name
          value: git-clone
        - name: namespace
          value: openshift-pipelines
      resolver: cluster
    workspaces:
      - name: output
        workspace: workspace-source

  - name: build-sign-image
    params:
      - name: IMAGE
        value: $(params.IMAGE)$(params.APP_NAME):$(params.TAG)
      - name: CONTEXT_DIR
        value: ./$(params.SOURCE_GIT_CONTEXT_DIR)
      - name: DOCKERFILE
        value: ./$(params.DOCKERFILE)
    runAfter:
      - fetch-repository
    taskRef:
      resolver: cluster
      params:
        - name: name
          value: buildah
    workspaces:
      - name: source
        workspace: workspace-source