apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipelines-ci
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: pipeline-ci
    server: 'https://kubernetes.default.svc'
  source:
    path: ci/pipeline
    repoURL: https://github.com/davidseve/poc-quarkus-applications.git
    targetRevision: improve #TODO HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false