apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: maven-build-
spec:
  taskRef:
    kind: ClusterTask
    name: maven
  params:
  - name: CONTEXT_DIR
    value: discounts
  - name: GOALS
    value:
    - clean
    - compile
    - package
  workspaces:
  - name: source
    persistentVolumeClaim:
      claimName: workspace-pvc
  - name: maven-settings
    emptyDir: {}