apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: build-image-
spec:
  taskRef:
    name: kaniko
  params:
  - name: IMAGE
    value: quay.io/dseveria/discounts
  - name: DOCKERFILE
    value: ./src/main/docker/Dockerfile.jvm
  - name: CONTEXT
    value: ./discounts
  workspaces:
  - name: source
    persistentVolumeClaim:
      claimName: workspace-pvc
  - name: dockerconfig
    secret:
      secretName: docker-config
