apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: example-helm-upgrade-from-source-
spec:
  taskRef:
    name: helm-upgrade-from-source
  params:
  - name: charts_dir
    value: discounts/helm
  - name: release_version
    value: v1.0.0
  - name: release_name
    value: discounts
  workspaces:
  - name: source
    persistentVolumeClaim:
      claimName: workspace-pvc-discounts